[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "Javascript"

[preprocessor.repl]
# iframe url
src = "https://mr-addict.github.io/mdbook-repl/embed/"

# enable javascript repl and lazy loading
javascript.enable = true
javascript.loading = "lazy"

[output.html.code.hidelines]
javascript = "~"
